import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#09090b",
        "surface-dim": "#0e0e13",
        "surface-bright": "#18181b",
        "surface-container-lowest": "#09090b",
        "surface-container-low": "#121219",
        "surface-container": "#18181b",
        "surface-container-high": "#1f1f24",
        "surface-container-highest": "#27272a",
        "on-surface": "#ffffff",
        "on-surface-variant": "#a1a1aa",
        "inverse-surface": "#ffffff",
        "inverse-on-surface": "#18181b",
        outline: "#71717a",
        "outline-variant": "#3f3f46",
        "surface-tint": "#8b5cf6",
        primary: "#a78bfa",
        "on-primary": "#ffffff",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#6e25f6",
        secondary: "#ecffe3",
        "on-secondary": "#003907",
        "secondary-container": "#13ff43",
        "on-secondary-container": "#007117",
        tertiary: "#ffb599",
        "on-tertiary": "#5a1c00",
        "tertiary-container": "#933300",
        "on-tertiary-container": "#ffb599",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbcff",
        "on-primary-fixed": "#22005d",
        "on-primary-fixed-variant": "#5400cc",
        "secondary-fixed": "#72ff70",
        "secondary-fixed-dim": "#00e639",
        "on-secondary-fixed": "#002203",
        "on-secondary-fixed-variant": "#00530e",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb599",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#7f2b00",
        background: "#09090b",
        "on-background": "#e2e8f0",
        "surface-variant": "#18181b",
        "status-optimal": "#00FF41",
        "status-latency": "#FFD300",
        "status-outage": "#FF3131",
        "surface-card": "#121219",
        "border-muted": "#27272a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "margin-desktop": "32px",
        "bento-gap": "12px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        grotesk: ["var(--font-hanken-grotesk)", "sans-serif"],
        inter: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "data-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      animation: {
        pulse: "statusPulse 2s infinite",
        spin: "spin 30s linear infinite",
        "spin-reverse": "spinReverse 30s linear infinite",
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
      },
      keyframes: {
        statusPulse: {
          "0%": { boxShadow: "0 0 0 0 rgba(0, 255, 65, 0.7)" },
          "70%": { boxShadow: "0 0 0 6px rgba(0, 255, 65, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(0, 255, 65, 0)" },
        },
        spin: {
          "100%": { transform: "rotate(360deg)" },
        },
        spinReverse: {
          "100%": { transform: "translateX(-50%) rotate(-360deg)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      backgroundImage: {
        "grid-pattern":
          "linear-gradient(rgba(42,42,53,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(42,42,53,0.5) 1px, transparent 1px)",
        "purple-glow": "radial-gradient(ellipse at center, rgba(98,0,234,0.2) 0%, transparent 70%)",
        "primary-gradient": "linear-gradient(135deg, #6200ea 0%, #9c27b0 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
